### ISSUE TITLE
Cannot connect to wpa 2 enterprise

### ISSUE THREAD

**Issue by HesselTjeerdsma** [JeroenBeemster/ESP32-WPA2-enterprise#1]
Hello,

I am trying to connect my esp32 to the eduroam network on my university, but got the following error:

sketch_sep22a:29: error: too few arguments to function 'esp_err_t esp_wifi_sta_wpa2_ent_enable(const esp_wpa2_config_t*)'

     esp_wifi_sta_wpa2_ent_enable();

I am using the arduino IDE 1.8.4, the esp32 wifi library version 1.0, and compile the code for the esp32 dev module.  Could you please help me solve this?

**Comment by ratnesht** [comment]
I have the same issue with connecting my esp32. :(

**Comment by HesselTjeerdsma** [comment]
I solved it by replacing:

`esp_wifi_sta_wpa2_ent_enable();`

with:
`esp_wpa2_config_t config = WPA2_CONFIG_INIT_DEFAULT();
    esp_wifi_sta_wpa2_ent_enable(&config);`

I also added my university email as EAP id, then I was able to connect.

**Comment by ratnesht** [comment]
@ HesselTjeerdsma : Smart! Working for me as well. Thanks a lot.

**Comment by mbenecke** [comment]
I would suggest to fix this example by a "pull request"

**Comment by ratnesht** [comment]
@ HesselTjeerdsma : I was able to connect the ESP32 with my university wifi but somehow it does not post the data to the server (e.g. emocms or IBM blumix). I am able to send the data to these servers if I use WPA2 instead of University wifi. Also, when I connect the wifi, I do get an IP address, which means the wifi is connected, but no data is sent to the server. Any suggestions??

**Comment by naikrovek** [comment]
@ratnesht sounds like there's a proxy on the University network that's supposed to take all outbound HTTP & HTTPS traffic and handle it for you.  This isn't present on the non-enterprise network, so it works there.  Same situation at my workplace.

**Comment by ratnesht** [comment]
Thanks,

I tried the same code at another work location (which has WPA2 enterprise)
and the code works there. The university's proxy doesnt let the device
connect. We asked for a workaround from the University IT team.

Ratnesh
